GRANT SELECT ON DBA_QLBV.BENHNHAN TO THANHTRA;
GRANT SELECT ON DBA_QLBV.NHANVIEN TO THANHTRA;
GRANT SELECT ON DBA_QLBV.HSBA TO THANHTRA;
GRANT SELECT ON DBA_QLBV.HSBA_DV TO THANHTRA;
GRANT SELECT ON DBA_QLBV.CSYT TO THANHTRA;
