--Tạo view trên bảng HSBA
CREATE OR REPLACE VIEW VIEW_NGHIENCUU_HSBA
AS SELECT MAHSBA, MABN, NGAY, CHANDOAN, MABS, MAKHOA, MACSYT, KETLUAN
    FROM HSBA
    WHERE MACSYT IN (SELECT CSYT FROM NHANVIEN WHERE MANV = SYS_CONTEXT('userenv', 'session_user'))
        AND MAKHOA IN (SELECT CHUYENKHOA FROM NHANVIEN WHERE MANV = SYS_CONTEXT('userenv', 'session_user'))
WITH CHECK OPTION;

--Tạo view trên bảng HSBA_DV
CREATE OR REPLACE VIEW VIEW_NGHIENCUU_HSBA_DV
AS SELECT MAHSBA, MADV, NGAY, MAKTV, KETQUA
    FROM HSBA_DV
    WHERE MAHSBA IN (SELECT MAHSBA FROM HSBA WHERE MACSYT IN (SELECT CSYT FROM NHANVIEN WHERE MANV = SYS_CONTEXT('userenv', 'session_user'))
                                                AND MAKHOA IN (SELECT CHUYENKHOA FROM NHANVIEN WHERE MANV = SYS_CONTEXT('userenv', 'session_user')))
WITH CHECK OPTION;

--Grant privilege trên view 
GRANT SELECT ON VIEW_NGHIENCUU_HSBA TO NGHIENCUU;
GRANT SELECT ON VIEW_NGHIENCUU_HSBA_DV TO NGHIENCUU;

--test
/*
SELECT MAHSBA, MADV, NGAY, MAKTV, KETQUA
    FROM HSBA_DV
    WHERE MAHSBA IN (SELECT MAHSBA FROM HSBA WHERE MACSYT IN (SELECT CSYT FROM NHANVIEN WHERE MANV = 'NV0029')
                                                AND MAKHOA IN (SELECT CHUYENKHOA FROM NHANVIEN WHERE MANV = 'NV0029'))
*/