--Tạo view trên bảng NHANVIEN
CREATE OR REPLACE VIEW VIEW_NHANVIEN_THONGTIN
AS SELECT MANV, HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA
    FROM NHANVIEN
    WHERE MANV = SYS_CONTEXT('userenv', 'session_user')
WITH CHECK OPTION;

--Tạo view trên bảng BENHNHAN
CREATE OR REPLACE VIEW VIEW_BENHNHAN_THONGTIN
AS SELECT MABN, MACSYT, TENBN, CMND, NGAYSINH, SONHA, TENDUONG, QUANHUYEN, TINHTP, TIENSUBENH, TIENSUBENHGD, DIUNGTHUOC
    FROM BENHNHAN
    WHERE MABN = SYS_CONTEXT('userenv', 'session_user')
WITH CHECK OPTION;

--Grant privilege trên view 
GRANT SELECT ON VIEW_NHANVIEN_THONGTIN TO NHANVIEN;
GRANT UPDATE (HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA) ON VIEW_NHANVIEN_THONGTIN TO NHANVIEN;

GRANT SELECT ON VIEW_BENHNHAN_THONGTIN TO BENHNHAN;
GRANT UPDATE (MACSYT, TENBN, CMND, NGAYSINH, SONHA, TENDUONG, QUANHUYEN, TINHTP, TIENSUBENH, TIENSUBENHGD, DIUNGTHUOC) ON VIEW_BENHNHAN_THONGTIN TO BENHNHAN;  

CREATE OR REPLACE VIEW NV_xem_thong_tin
AS 
(
  SELECT MANV,HOTEN,PHAI,NGAYSINH, CMND,QUEQUAN,GIAI_MA(SODT,'A1A2A3A4A5A6CAFE') as SODT, CSYT,vaitro,chuyenkhoa
  FROM NHANVIEN 
  WHERE upper(MANV) = USER
);
CREATE OR Replace PUBLIC SYNONYM NV_xem_thong_tin FOR DBA_QLBV.NV_xem_thong_tin;
GRANT SELECT, UPDATE ON NV_xem_thong_tin TO THANHTRA;
--Test
select * from DBA_QLBV.NV_xem_thong_tin;