--Tạo role Nhân viên
CREATE ROLE ROLE_NHANVIEN;
SET ROLE ROLE_NHANVIEN;
GRANT CREATE SESSION TO ROLE_NHANVIEN;

--Tạo role Bệnh nhân
CREATE ROLE ROLE_BENHNHAN;
SET ROLE ROLE_BENHNHAN;
GRANT CREATE SESSION TO ROLE_BENHNHAN;

--Tạo view trên bảng NHANVIEN
CREATE OR REPLACE VIEW VIEW_NHANVIEN_THONGTIN
AS SELECT MANV, HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA
    FROM NHANVIEN
    WHERE MANV = SYS_CONTEXT('userenv', 'session_user')
WITH CHECK OPTION;

--Tạo view trên bảng BENHNHAN
CREATE OR REPLACE VIEW VIEW_BENHNHAN_THONGTIN
AS SELECT MABN, MACSYT, TENBN, CMND, NGAYSINH, SONHA, TENDUONG, QUANHUYEN, TINHTP, TIENSUBENH, TIENSUBENHGD, DIUNGTHUOC
    FROM BENHNHAN
    WHERE MABN = SYS_CONTEXT('userenv', 'session_user')
WITH CHECK OPTION;

--Grant privilege trên view 
GRANT SELECT ON VIEW_NHANVIEN_THONGTIN TO ROLE_NHANVIEN;
GRANT UPDATE (HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA) ON VIEW_NHANVIEN_THONGTIN TO ROLE_NHANVIEN;

GRANT SELECT ON VIEW_BENHNHAN_THONGTIN TO ROLE_BENHNHAN;
GRANT UPDATE (MACSYT, TENBN, CMND, NGAYSINH, SONHA, TENDUONG, QUANHUYEN, TINHTP, TIENSUBENH, TIENSUBENHGD, DIUNGTHUOC) ON VIEW_BENHNHAN_THONGTIN TO ROLE_BENHNHAN;  