--HỆ THỐNG THÔNG TIN QUẢN LÝ BỆNH VIỆN S--

--Xóa bảng
/*
DROP TABLE HSBA_DV CASCADE CONSTRAINTS;
DROP TABLE HSBA CASCADE CONSTRAINTS;
DROP TABLE BENHNHAN CASCADE CONSTRAINTS;
DROP TABLE NHANVIEN CASCADE CONSTRAINTS;
DROP TABLE CSYT CASCADE CONSTRAINTS;
DROP TABLE CHUYENKHOA CASCADE CONSTRAINTS;
DROP TABLE DICHVU CASCADE CONSTRAINTS;
*/

alter session set "_ORACLE_SCRIPT"=true;

--Tạo bảng
CREATE TABLE HSBA
(
    MAHSBA CHAR(6),
    MABN CHAR(6),
    NGAY DATE,
    CHANDOAN NVARCHAR2(250),
    MABS CHAR(6),
    MAKHOA CHAR(6),
    MACSYT CHAR(6),
    KETLUAN NVARCHAR2(250),
    CONSTRAINT PK_HSBA PRIMARY KEY (MAHSBA) 
);

CREATE TABLE HSBA_DV
(
    MAHSBA CHAR(6),
    MADV CHAR(6),
    NGAY DATE,
    MAKTV CHAR(6),
    KETQUA NVARCHAR2(250),
    CONSTRAINT PK_HSBADV PRIMARY KEY (MAHSBA, MADV, NGAY) 
);

CREATE TABLE BENHNHAN
(
    MABN CHAR(6),
    MACSYT CHAR(6),
    TENBN NVARCHAR2(150), 
    CMND VARCHAR2(15),
    NGAYSINH DATE,
    SONHA VARCHAR2(10),
    TENDUONG NVARCHAR2(50),
    QUANHUYEN NVARCHAR2(50),
    TINHTP NVARCHAR2(50),
    TIENSUBENH NVARCHAR2(250),
    TIENSUBENHGD NVARCHAR2(250),
    DIUNGTHUOC NVARCHAR2(250),
    CONSTRAINT PK_BENHNHAN PRIMARY KEY (MABN) 
);

CREATE TABLE CSYT
(
    MACSYT CHAR(6),
    TENCSYT NVARCHAR2(150), 
    DCCSYT NVARCHAR2(250),
    SDTCSYT NVARCHAR2(12),
    CONSTRAINT PK_CSYT PRIMARY KEY (MACSYT) 
);

CREATE TABLE NHANVIEN
(
    MANV CHAR(6),
    HOTEN NVARCHAR2(150), 
    PHAI NVARCHAR2(4),
    NGAYSINH DATE,
    CMND VARCHAR2(15),
    QUEQUAN NVARCHAR2(250),
    SODT VARCHAR2(12),
    CSYT CHAR(6),
    VAITRO NVARCHAR2(100),
    CHUYENKHOA CHAR(6),
    CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANV) 
);

CREATE TABLE CHUYENKHOA(
    MAKHOA CHAR(6),
    TENKHOA NVARCHAR2(20),
    CONSTRAINT CHUYENKHOA_PK PRIMARY KEY ( MAKHOA )
);

CREATE TABLE DICHVU(
    MADV CHAR(6),
    TENDICHVU NVARCHAR2(30),
    CONSTRAINT DICHVU_PK PRIMARY KEY ( MADV)
);

--Thêm khóa ngoại và ràng buộc
ALTER TABLE HSBA ADD
    CONSTRAINT FK_HSBA_BENHNHAN FOREIGN KEY(MABN) REFERENCES BENHNHAN(MABN);
ALTER TABLE HSBA ADD
    CONSTRAINT FK_HSBA_NHANVIEN FOREIGN KEY(MABS) REFERENCES NHANVIEN(MANV);
ALTER TABLE HSBA ADD
    CONSTRAINT FK_HSBA_CSYT FOREIGN KEY(MACSYT) REFERENCES CSYT(MACSYT);
ALTER TABLE HSBA ADD
    CONSTRAINT FK_HSBA_CHUYENKHOA FOREIGN KEY(MAKHOA) REFERENCES CHUYENKHOA(MAKHOA);

ALTER TABLE HSBA_DV ADD 
    CONSTRAINT FK_HSBADV_HSBA FOREIGN KEY(MAHSBA) REFERENCES HSBA(MAHSBA);
ALTER TABLE HSBA_DV ADD
    CONSTRAINT FK_HSBADV_NHANVIEN FOREIGN KEY(MAKTV) REFERENCES NHANVIEN(MANV);
ALTER TABLE HSBA_DV ADD 
    CONSTRAINT FK_HSBADV_DICHVU FOREIGN KEY(MADV) REFERENCES DICHVU(MADV);
    
ALTER TABLE BENHNHAN ADD
    CONSTRAINT FK_BENHNHAN_CSYT FOREIGN KEY(MACSYT) REFERENCES CSYT(MACSYT);
    
ALTER TABLE NHANVIEN ADD
    CONSTRAINT FK_NHANVIEN_CSYT FOREIGN KEY(CSYT) REFERENCES CSYT(MACSYT);
ALTER TABLE NHANVIEN ADD
    CONSTRAINT FK_NHANVIEN_VAITRO CHECK (VAITRO IN (N'Thanh tra', N'Cơ sở y tế', N'Y sĩ/Bác sĩ', N'Nghiên cứu'));
    
--Tạo role bệnh nhân
CREATE ROLE BENHNHAN NOT IDENTIFIED;
SET ROLE BENHNHAN;
GRANT CREATE SESSION TO BENHNHAN;

--Tao role nhân viên
CREATE ROLE NHANVIEN NOT IDENTIFIED;
SET ROLE NHANVIEN;
GRANT CREATE SESSION TO NHANVIEN;

--Tao role y bác sĩ
CREATE ROLE Y_BACSI;
SET ROLE Y_BACSI;
GRANT CREATE SESSION TO Y_BACSI;

--Tạo role thanh tra
CREATE ROLE THANHTRA;
SET ROLE THANHTRA;
GRANT CREATE SESSION TO THANHTRA;

--Tạo role quản lý
CREATE ROLE CSYT;
SET ROLE CSYT;
GRANT CREATE SESSION TO CSYT;

--Tạo role nghiên cứu
CREATE ROLE NGHIENCUU;
SET ROLE NGHIENCUU;
GRANT CREATE SESSION TO NGHIENCUU;
